name: Create release


permissions: write-all

on:
  push:
    tags:
      - 'v*'

jobs:
  create_release:
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  upload-windows-installer:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./scripts/sherry-windows-install.ps1
          asset_name: sherry-windows-install.ps1
          asset_content_type: text/plain

  build-windows:
    permissions: write-all
    runs-on: windows-latest
    needs: create_release
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.6'
      - name: Build
        run: go build -ldflags "-s -w"
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: shr.exe
          asset_name: shr.exe
          asset_content_type: application/vnd.microsoft.portable-executable

  build-linux:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.6'
      - name: Build
        run: go build -ldflags "-s -w"
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: shr
          asset_name: shr-linux
          asset_content_type: application/x-elf

  build-macos:
    permissions: write-all
    runs-on: macos-latest
    needs: create_release
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.6'
      - name: Build
        run: go build -ldflags "-s -w"
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: shr
          asset_name: shr-macos
          asset_content_type: application/x-elf
